from django.urls import path
from . import views

urlpatterns = [
    path('check_user/', views.check_user, name='check_user'),
    path('new-products/', views.new_product, name='new_products'),
    path('', views.home, name='home'),  
    path('search/', views.search, name='search'),  
    path('contact/', views.contact, name='contact'),  
    path('about/', views.about, name='about'),  
     path('section/<str:cate>/', views.section, name='section'),  
    path('product/<int:id>/', views.show_product, name='show_product'),
    path('get_available_colors/', views.get_available_colors, name='get_available_colors'),
    path('check_stock_quantity/', views.check_stock_quantity, name='check_stock_quantity'),
    path('addcart/<int:id>/', views.addcart, name='addcart'),
    path('removecart/<int:id>/', views.removecart, name='removecart'),
    path('cart/', views.cart, name='cart'),
    path('get_colors/', views.get_colors, name='get_colors'),
    path('updatecart/', views.updatecart, name='updatecart'),
    path('checkout/', views.checkout, name='checkout'),
    path('address/', views.address, name='address'),
    path('place_order/', views.place_order, name='place_order'),
    path('order_confirm/<str:hasher_id>/', views.order_confirm, name='order_confirm'),
    path('order_history/', views.order_history, name='order_history'),
    path('return_order/<int:order_id>/', views.return_order, name='return_order'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('invoice/<int:order_id>/', views.invoice, name='invoice'),
    path('generate_invoice/<int:order_id>/', views.generate_invoice, name='generate_invoice'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('logout/', views.logout_cus, name='logout'),
]